version: "3.8"

services:
  postgres:
    build: ./postgres
    container_name: postgres_container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=satisfacao_db
    ports:
      - "5432:5432"
    networks:
      - tf-network

  mongodb:
    build: ./mongodb
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - "27017:27017"
    networks:
      - tf-network

  nodejs:
    build: ./nodejs
    container_name: nodejs_container
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    networks:
      - tf-network

networks:
  tf-network:
    driver: bridge
